[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[theme]
primaryColor = "#5FA83D"
backgroundColor = "#f4f7f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#0A2540"
